"""Exports for admin UI routers."""

from . import (
    api,
    candidate_portal,
    candidates,
    cities,
    content_api,
    dashboard,
    detailization,
    directory,
    hh_integration,
    recruiters,
    profile_api,
    slots,
    slot_assignments,
    system,
    simulator,
    questions,
    message_templates,
)  # noqa: F401

__all__ = [
    "api",
    "candidate_portal",
    "candidates",
    "cities",
    "content_api",
    "dashboard",
    "detailization",
    "directory",
    "hh_integration",
    "profile_api",
    "recruiters",
    "slots",
    "slot_assignments",
    "system",
    "simulator",
    "questions",
    "message_templates",
]
