"""Add candidate lifecycle, journey events, final outcomes, and reporting fields."""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.engine import Connection

from backend.migrations.utils import column_exists, index_exists, table_exists

revision = "0097_add_candidate_journey_archive_foundation"
down_revision = "0096_add_candidate_chat_workspaces"
branch_labels = None
depends_on = None


def _add_column_if_missing(conn: Connection, table: str, column_sql: str, column_name: str) -> None:
    if table_exists(conn, table) and not column_exists(conn, table, column_name):
        conn.execute(sa.text(f"ALTER TABLE {table} ADD COLUMN {column_sql}"))


def _create_candidate_journey_events(conn: Connection) -> None:
    if table_exists(conn, "candidate_journey_events"):
        return
    conn.execute(
        sa.text(
            """
            CREATE TABLE candidate_journey_events (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                candidate_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                event_key VARCHAR(80) NOT NULL,
                stage VARCHAR(32) NOT NULL,
                status_slug VARCHAR(64),
                actor_type VARCHAR(32),
                actor_id INTEGER,
                summary VARCHAR(255),
                payload_json JSON,
                created_at TIMESTAMP
            )
            """
        )
    )


def _ensure_candidate_journey_events_id_identity(conn: Connection) -> None:
    if not table_exists(conn, "candidate_journey_events"):
        return

    result = conn.execute(
        sa.text(
            """
            SELECT is_identity, column_default
            FROM information_schema.columns
            WHERE table_name = 'candidate_journey_events'
              AND column_name = 'id'
            """
        )
    ).mappings().first()

    if not result:
        return

    is_identity = (result.get("is_identity") or "").upper() == "YES"
    column_default = result.get("column_default")
    if is_identity or column_default:
        return

    conn.execute(
        sa.text(
            """
            ALTER TABLE candidate_journey_events
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
            """
        )
    )


def _create_indexes(conn: Connection) -> None:
    if table_exists(conn, "users") and not index_exists(conn, "users", "ix_users_lifecycle_state"):
        conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_users_lifecycle_state ON users (lifecycle_state)"))
    if table_exists(conn, "candidate_journey_events") and not index_exists(
        conn,
        "candidate_journey_events",
        "ix_candidate_journey_events_candidate_created",
    ):
        conn.execute(
            sa.text(
                """
                CREATE INDEX IF NOT EXISTS ix_candidate_journey_events_candidate_created
                ON candidate_journey_events (candidate_id, created_at)
                """
            )
        )
    if table_exists(conn, "candidate_journey_events") and not index_exists(
        conn,
        "candidate_journey_events",
        "ix_candidate_journey_events_event_key",
    ):
        conn.execute(
            sa.text(
                """
                CREATE INDEX IF NOT EXISTS ix_candidate_journey_events_event_key
                ON candidate_journey_events (event_key)
                """
            )
        )


def _backfill_users(conn: Connection) -> None:
    if not table_exists(conn, "users"):
        return

    conn.execute(
        sa.text(
            """
            UPDATE users
            SET lifecycle_state = COALESCE(lifecycle_state, 'active')
            WHERE lifecycle_state IS NULL OR TRIM(COALESCE(lifecycle_state, '')) = ''
            """
        )
    )

    conn.execute(
        sa.text(
            """
            UPDATE users
            SET
                lifecycle_state = 'archived',
                archive_stage = CASE
                    WHEN candidate_status = 'interview_declined' THEN 'interview'
                    WHEN candidate_status = 'test2_failed' THEN 'test2'
                    WHEN candidate_status IN ('intro_day_declined_invitation', 'intro_day_declined_day_of') THEN 'intro_day'
                    WHEN candidate_status = 'not_hired' THEN 'outcome'
                    ELSE archive_stage
                END,
                archive_reason = COALESCE(
                    NULLIF(TRIM(COALESCE(archive_reason, '')), ''),
                    NULLIF(TRIM(COALESCE(rejection_reason, '')), ''),
                    NULLIF(TRIM(COALESCE(intro_decline_reason, '')), ''),
                    NULLIF(TRIM(COALESCE(final_outcome_reason, '')), '')
                ),
                archived_at = COALESCE(archived_at, rejected_at, status_changed_at, CURRENT_TIMESTAMP)
            WHERE candidate_status IN (
                'interview_declined',
                'test2_failed',
                'intro_day_declined_invitation',
                'intro_day_declined_day_of',
                'not_hired'
            )
            """
        )
    )

    conn.execute(
        sa.text(
            """
            UPDATE users
            SET
                lifecycle_state = 'active',
                archive_stage = NULL,
                archive_reason = NULL,
                archived_at = NULL
            WHERE candidate_status IS NULL
               OR candidate_status NOT IN (
                    'interview_declined',
                    'test2_failed',
                    'intro_day_declined_invitation',
                    'intro_day_declined_day_of',
                    'not_hired'
               )
            """
        )
    )

    conn.execute(
        sa.text(
            """
            UPDATE users
            SET
                final_outcome = 'attached',
                final_outcome_reason = NULLIF(TRIM(COALESCE(final_outcome_reason, '')), '')
            WHERE candidate_status = 'hired'
            """
        )
    )

    conn.execute(
        sa.text(
            """
            UPDATE users
            SET
                final_outcome = CASE
                    WHEN LOWER(COALESCE(final_outcome_reason, intro_decline_reason, rejection_reason, '')) LIKE '%не засчит%'
                      OR LOWER(COALESCE(final_outcome_reason, intro_decline_reason, rejection_reason, '')) LIKE '%не подлежит оплат%'
                      OR LOWER(COALESCE(final_outcome_reason, intro_decline_reason, rejection_reason, '')) LIKE '%не приш%'
                      OR LOWER(COALESCE(final_outcome_reason, intro_decline_reason, rejection_reason, '')) LIKE '%не яв%'
                      OR LOWER(COALESCE(final_outcome_reason, intro_decline_reason, rejection_reason, '')) LIKE '%no show%'
                      OR LOWER(COALESCE(final_outcome_reason, intro_decline_reason, rejection_reason, '')) LIKE '%no_show%'
                    THEN 'not_counted'
                    ELSE 'not_attached'
                END,
                final_outcome_reason = COALESCE(
                    NULLIF(TRIM(COALESCE(final_outcome_reason, '')), ''),
                    NULLIF(TRIM(COALESCE(intro_decline_reason, '')), ''),
                    NULLIF(TRIM(COALESCE(rejection_reason, '')), '')
                )
            WHERE candidate_status IN (
                'not_hired',
                'intro_day_declined_invitation',
                'intro_day_declined_day_of'
            )
            """
        )
    )


def _backfill_detailization(conn: Connection) -> None:
    if not table_exists(conn, "detailization_entries"):
        return

    conn.execute(
        sa.text(
            """
            UPDATE detailization_entries
            SET final_outcome = CASE
                WHEN is_attached IS TRUE THEN 'attached'
                WHEN is_attached IS FALSE THEN 'not_attached'
                ELSE final_outcome
            END
            WHERE final_outcome IS NULL
            """
        )
    )


def _backfill_slot_origins(conn: Connection) -> None:
    if table_exists(conn, "slot_assignments"):
        conn.execute(
            sa.text(
                """
                UPDATE slot_assignments
                SET origin = COALESCE(NULLIF(TRIM(COALESCE(origin, '')), ''), 'bot')
                """
            )
        )
    if table_exists(conn, "slot_reschedule_requests"):
        conn.execute(
            sa.text(
                """
                UPDATE slot_reschedule_requests
                SET origin = COALESCE(NULLIF(TRIM(COALESCE(origin, '')), ''), 'candidate')
                """
            )
        )


def _backfill_status_events(conn: Connection) -> None:
    if not table_exists(conn, "candidate_journey_events") or not table_exists(conn, "users"):
        return

    conn.execute(
        sa.text(
            """
            INSERT INTO candidate_journey_events (
                candidate_id,
                event_key,
                stage,
                status_slug,
                actor_type,
                summary,
                payload_json,
                created_at
            )
            SELECT
                u.id,
                'status_backfill',
                CASE
                    WHEN u.candidate_status IN ('lead', 'contacted', 'invited') THEN 'lead'
                    WHEN u.candidate_status IN ('test1_completed', 'waiting_slot', 'stalled_waiting_slot', 'test2_sent', 'test2_completed', 'test2_failed') THEN 'testing'
                    WHEN u.candidate_status IN ('slot_pending', 'interview_scheduled', 'interview_confirmed', 'interview_declined') THEN 'interview'
                    WHEN CAST(u.candidate_status AS TEXT) LIKE 'intro_day_%' THEN 'intro_day'
                    WHEN u.candidate_status IN ('hired', 'not_hired') THEN 'outcome'
                    ELSE 'lead'
                END,
                u.candidate_status,
                'migration',
                'Initial backfill from current candidate status',
                NULL,
                COALESCE(u.status_changed_at, u.rejected_at, CURRENT_TIMESTAMP)
            FROM users u
            WHERE u.candidate_status IS NOT NULL
              AND NOT EXISTS (
                    SELECT 1
                    FROM candidate_journey_events e
                    WHERE e.candidate_id = u.id
                      AND e.event_key = 'status_backfill'
              )
            """
        )
    )


def upgrade(conn: Connection) -> None:
    _add_column_if_missing(conn, "users", "lifecycle_state VARCHAR(16) DEFAULT 'active' NOT NULL", "lifecycle_state")
    _add_column_if_missing(conn, "users", "archive_stage VARCHAR(64)", "archive_stage")
    _add_column_if_missing(conn, "users", "archive_reason TEXT", "archive_reason")
    _add_column_if_missing(conn, "users", "archived_at TIMESTAMP", "archived_at")
    _add_column_if_missing(conn, "users", "final_outcome VARCHAR(32)", "final_outcome")
    _add_column_if_missing(conn, "users", "final_outcome_reason TEXT", "final_outcome_reason")

    _add_column_if_missing(conn, "detailization_entries", "final_outcome VARCHAR(32)", "final_outcome")
    _add_column_if_missing(conn, "detailization_entries", "final_outcome_reason TEXT", "final_outcome_reason")

    _add_column_if_missing(conn, "slot_assignments", "origin VARCHAR(24) DEFAULT 'bot' NOT NULL", "origin")
    _add_column_if_missing(conn, "slot_reschedule_requests", "origin VARCHAR(24) DEFAULT 'candidate' NOT NULL", "origin")

    _create_candidate_journey_events(conn)
    _ensure_candidate_journey_events_id_identity(conn)
    _create_indexes(conn)
    _backfill_users(conn)
    _backfill_detailization(conn)
    _backfill_slot_origins(conn)
    _backfill_status_events(conn)


def downgrade(conn: Connection) -> None:  # pragma: no cover
    if table_exists(conn, "candidate_journey_events"):
        conn.execute(sa.text("DROP TABLE candidate_journey_events"))
