name: UI Preview

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"
      - name: Install Node dependencies
        run: npm ci
      - name: Build CSS
        run: npm run build:css
      - name: Install Playwright browsers
        run: playwright install --with-deps
      - name: Render previews
        run: python tools/render_previews.py
      - name: Capture UI screenshots
        run: pytest tests/test_ui_screenshots.py
      - name: Upload previews
        uses: actions/upload-artifact@v4
        with:
          name: ui-previews
          path: previews
          if-no-files-found: ignore
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: ui-screenshots
          path: ui_screenshots
          if-no-files-found: ignore
      - name: Ensure repository stays clean
        run: |
          git status --short
          git diff --cached --exit-code
